### ISSUE TITLE
How does the ndef applet work with iOS Core NFC?

### ISSUE THREAD

**Issue by johnnytshi** [status-im/hardware-wallet#6]
i am a bit confused how the ndef works.

How does NDEF know to select the applet? or is the applet id standard?

All the best!

Johnny

**Comment by bitgamma** [comment]
The NDEF applet has a standard AID. However, at the moment our applet only return an Android Application Record, which does not work with iOS. Since iOS does not support the Hardware Wallet Lite anyway this should not be a problem.

Eventually a mechanism to dynamically update the content of the NDEF record could be implemented.

**Comment by johnnytshi** [comment]
thanks for the reply!

"Since iOS does not support the Hardware Wallet Lite anyway this should not be a problem." is that a limitation on iOS side? I know Core NFC is supposed to be able to read NDEF data.

**Comment by bitgamma** [comment]
Yeah it is an iOS limitation. It can read NDEF data but it does not allow apps sending custom ISO7816 APDUs, which are needed for the hardwallet.
